#!/bin/bash

PROP_FILE="env.properties"  # Explicitly use relative path

if [[ -f "$PROP_FILE" && -r "$PROP_FILE" ]]; then  # Check if file is readable

    # shellcheck disable=SC1090
    . "$PROP_FILE"  # Source the file
fi

if [ -z "$1" ]; then

  if [ -z "$DEFAULT_COMMIT_MESSAGE" ]; then

    MESSAGE="Auto-commit."

  else

    MESSAGE="$DEFAULT_COMMIT_MESSAGE"
  fi

else

  if [ -z "$PROJECT_NAME" ]; then

      MESSAGE="$1"

  else

    MESSAGE="$PROJECT_NAME - $1"
  fi
fi

echo "Pushing: '$MESSAGE'" && \
  commit "$MESSAGE" && \
  echo "Push with message '$MESSAGE' completed"